#!/usr/bin/env python3
"""Build made elements through the mesh pipeline, and only those.

    tools/build_custom.py PART.dat ... --out DIR       their meshes and entries
    tools/build_custom.py MODEL.mpd --out DIR          the parts embedded in it
    tools/build_custom.py PART.dat ... --summary FILE  what the pipeline made
    tools/build_custom.py PART.dat ... --into DIR      add them to a catalogue

A full tools/build_meshes.py run is ninety minutes for twenty-seven
thousand parts. A part made in the element maker is one file the library
has never seen, so this builds that file with the same conversion the full
build uses (build_meshes._convert: flatten, connectors from the primitives,
voxelise, remove the studs, fill the cavities, cover with boxes, find the
sockets) and nothing else. It takes seconds.

The parts come from anywhere an LDraw part can be: a .dat the app saved
under its user directory, a fixture, or a model file. A .mpd made in the
app carries its custom parts inside it as `0 FILE <id>.dat` sections, as
the LDraw multi-part document spec allows, and they are taken out of it
here.

--out writes DIR/parts/<hash>.lbm and DIR/custom.json, catalogue entries
in the same shape as catalogue.json's, filed under "Custom".

--into merges them into DIR/catalogue.json (assets/generated by default
is *not* assumed: name it), copies the meshes into DIR/parts and the
sources into DIR/custom, so a made part can ship as one of the library's
own. It replaces an entry of the same id and leaves every other entry as
it was, so tools/refresh_catalogue.py is not needed after it.

--summary writes what the pipeline made of each part as plain numbers —
bounds, connectors, collision boxes, sockets, cells — which is what
src/dev/element_files_probe.gd holds the app's own build of the same file
against.

Needs numpy and scipy, as the full build does.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

from ldraw.library import Library  # noqa: E402

LDRAW = ROOT / "vendor" / "ldraw"


def parts_in(paths: list[Path], into: Path) -> list[Path]:
    """The part files to build: .dat files as given, and every part
    embedded in a .mpd or .ldr, written out to ``into``."""
    found: list[Path] = []
    for path in paths:
        if path.suffix.lower() == ".dat":
            found.append(path)
            continue
        for name, text in embedded_parts(path.read_text(encoding="latin-1")).items():
            target = into / name
            target.write_text(text, encoding="latin-1")
            found.append(target)
    return found


def embedded_parts(text: str) -> dict[str, str]:
    """The `0 FILE` sections of a multi-part document that are parts
    rather than sub-models: named .dat, or declaring themselves a part in
    !LDRAW_ORG. Keyed by file name, lower case."""
    sections: dict[str, list[str]] = {}
    current: list[str] | None = None
    for line in text.splitlines():
        words = line.split()
        if len(words) >= 3 and words[0] == "0" and words[1].upper() == "FILE":
            name = " ".join(words[2:]).strip().lower()
            current = sections.setdefault(name, [])
            continue
        if len(words) >= 2 and words[0] == "0" and words[1].upper() == "NOFILE":
            current = None
            continue
        if current is not None:
            current.append(line)
    parts: dict[str, str] = {}
    for name, lines in sections.items():
        body = "\n".join(lines) + "\n"
        declared = any(
            l.split()[:2] == ["0", "!LDRAW_ORG"] and "part" in l.lower()
            for l in lines[:12] if l.strip())
        if name.endswith(".dat") or declared:
            parts[name if name.endswith(".dat") else name + ".dat"] = body
    return parts


def build(files: list[Path]) -> list[tuple[str, bytes, dict, str]]:
    """Each part through build_meshes' own conversion.

    Returns (id, mesh bytes, catalogue record, source text) per part, and
    raises if any part fails — a made part that does not build is a fault
    in the maker, not something to skip past.
    """
    import build_meshes  # numpy and scipy, which embedded_parts does not need
    folders = sorted({str(f.parent.resolve()) for f in files})
    build_meshes._LIBRARY = Library(LDRAW, extra=folders)
    out = []
    for path in files:
        part_id, blob, record = build_meshes._convert(path.name.lower())
        if blob is None:
            raise SystemExit(f"{path}: {record.get('error')}")
        out.append((part_id, blob, record, path.read_text(encoding="latin-1")))
    return out


def summary(part_id: str, blob: bytes) -> dict:
    """What the pipeline made of one part, as numbers to compare, and the
    SHA-256 of the .lbm it wrote, which the app's build has to equal byte
    for byte.

    The numbers are recomputed rather than read back from the .lbm,
    because the .lbm keeps its bounds as 32-bit floats and the comparison
    wants what the conversion worked with.
    """
    import build_meshes
    from ldraw import meshfile
    from ldraw import occupancy as occ
    from ldraw.connectivity import extract
    from ldraw.geometry import flatten

    library = build_meshes._LIBRARY
    assert library is not None
    name = part_id + ".dat"
    mesh = flatten(library, name)
    part = meshfile.build(mesh)
    connections = extract(library, name)
    solid = occ.fill_cavities(
        occ.remove_studs(occ.voxelise(mesh), connections), connections)
    connectors = sorted(
        [c.kind.value, c.gender.value,
         [_r(c.position.x), _r(-c.position.y), _r(-c.position.z)],
         [_r(c.axis.x), _r(-c.axis.y), _r(-c.axis.z)]]
        for c in connections)
    return {
        "bounds_min": [_r(v) for v in part.bounds_min],
        "bounds_max": [_r(v) for v in part.bounds_max],
        "triangles": part.triangle_count,
        "connectors": connectors,
        "boxes": sorted([int(v) for v in box] for box in occ.to_boxes(solid)),
        "sockets": sorted([_r(x), _r(z)] for x, z in occ.bottom_sockets(solid)),
        "cells": solid.cell_count,
        "lbm_sha256": hashlib.sha256(blob).hexdigest(),
    }


def _r(value: float) -> float:
    """Three places, and never -0.0, which JSON would keep."""
    rounded = round(float(value), 3)
    return 0.0 if rounded == 0 else rounded


def custom_record(record: dict, source_name: str) -> dict:
    """A catalogue entry for a made part: filed under Custom, keeping the
    category its own header gives it, and saying where its source is."""
    entry = dict(record)
    entry["ldraw_category"] = record.get("category", "")
    entry["category"] = "Custom"
    entry["custom"] = True
    entry["source"] = "custom/" + source_name
    entry["unofficial"] = True
    return entry


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("files", nargs="+", type=Path)
    parser.add_argument("--out", type=Path)
    parser.add_argument("--into", type=Path)
    parser.add_argument("--summary", type=Path)
    args = parser.parse_args()
    if not (args.out or args.into or args.summary):
        parser.error("say where: --out, --into or --summary")

    with tempfile.TemporaryDirectory() as scratch:
        files = parts_in(args.files, Path(scratch))
        if not files:
            print("no parts in " + " ".join(str(f) for f in args.files))
            return 1
        built = build(files)
        for part_id, blob, record, _source in built:
            counts = record["connector_counts"]
            print(f"  {part_id:18} {record['name']:34} "
                  f"{counts.get('stud', 0):3} studs  {record['socket_count']:3} sockets  "
                  f"{record['box_count']:3} boxes  {record['triangles']:5} triangles")

        if args.summary:
            parts = {part_id: summary(part_id, blob) for part_id, blob, *_ in built}
            args.summary.write_text(json.dumps(
                {"from": "tools/build_custom.py", "parts": parts},
                indent=1, sort_keys=True) + "\n")
            print(f"wrote {args.summary} ({len(parts)} parts)")

        for where in (args.out, args.into):
            if where is None:
                continue
            (where / "parts").mkdir(parents=True, exist_ok=True)
            for _part_id, blob, record, _source in built:
                (where / "parts" / f"{record['mesh']}.lbm").write_bytes(blob)

        if args.out:
            entries = [custom_record(record, part_id + ".dat")
                       for part_id, _blob, record, _source in built]
            (args.out / "custom").mkdir(exist_ok=True)
            for part_id, _blob, _record, source in built:
                (args.out / "custom" / f"{part_id}.dat").write_text(
                    source, encoding="latin-1")
            (args.out / "custom.json").write_text(
                json.dumps({"format": 1, "parts": entries}, separators=(",", ":")))
            print(f"wrote {len(entries)} parts to {args.out}")

        if args.into:
            catalogue = args.into / "catalogue.json"
            if not catalogue.exists():
                print(f"no catalogue at {catalogue}")
                return 1
            document = json.loads(catalogue.read_text())
            fresh = {part_id: custom_record(record, part_id + ".dat")
                     for part_id, _blob, record, _source in built}
            replaced = sum(1 for e in document["parts"] if e["id"] in fresh)
            document["parts"] = [e for e in document["parts"]
                                 if e["id"] not in fresh] + list(fresh.values())
            document["parts"].sort(key=lambda e: e["id"])
            document["counts"]["parts"] = len(document["parts"])
            (args.into / "custom").mkdir(exist_ok=True)
            for part_id, _blob, _record, source in built:
                (args.into / "custom" / f"{part_id}.dat").write_text(
                    source, encoding="latin-1")
            catalogue.write_text(json.dumps(document, separators=(",", ":")))
            print(f"merged {len(fresh)} parts into {catalogue} "
                  f"({replaced} replaced, {len(document['parts']):,} in all)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
